training:
  seed: 42

  batch_size: 8
  num_workers: 16
  max_epochs: 100

  strategy: auto
  devices: [0]
  precision: 32

  monitor: val_loss
  grad_clip_val: 1.0

  lr: 0.001
  weight_decay: 0.0
  scheduler:
    type: cosine
    T_max: 50

  losses:
    stft_losses:
      foa_active_intensity_doa:
        weight: 0.2
      foa_energy_ratio:
        weight: 0.05
        ratio_type: directional_to_total

    wave_losses:
      multi_resolution_stft:
        weight: 1.0
        fft_sizes: [512, 1024, 2048]
        hop_sizes: [128, 256, 512]
        win_lengths: [512, 1024, 2048]
      si_sdr:
        weight: 0.2
      foa_covariance:
        weight: 0.2
        normalize: fro
        loss_type: l1

  masking: complex
