training:
  seed: 42

  batch_size: 8
  num_workers: 16
  max_epochs: 100

  strategy: auto
  devices: [0]
  precision: 32

  monitor: val_loss
  grad_clip_val: 1.0

  lr: 0.001
  weight_decay: 0.0
  scheduler:
    type: cosine
    T_max: 50

  losses:
    stft_losses:
      l1:
        weight: 1.0
      magnitude:
        weight: 1.0
    wave_losses:
      si_sdr:
        reduction: mean
        eps: 1e-9
        weight: 0.05

  masking: complex
